
// responses.js
module.exports = [
  
  // randam ＝ ランダムで1個送信
  {
    pattern: /きょへ。?は/,
    responses: ["# ピカ知識レート2500。\n# 元ピカチュウ窓ﾇﾁ!!\nhttps://cdn.discordapp.com/attachments/1022093564995436594/1086669279233069076/kyohe.gif",
                "sky知識レート2500。skyを始めてから登録者数が爆増し\nチャンネル登録者数は驚愕の…！ERR_CONNECTION_RESET ⚠人達成！！",
                "sky知識レート2500。skyを始めてから登録者数が爆増し\nチャンネル登録者数は驚愕の…！err: response timeout after 504ms 人達成！！",
                "# 彼の名は「きょへ。」\n趣味はキャンマラ…ではなくキャンマラのルート構成らしい。\n人間のフリをした歩くバグ。",
                "現実ではポンコツ、ゲームでは中の上。毎日引きこもってます。",
                "・常に数手先を読んでる思考のスナイパー。\n・冷静・論理的だけど、実は内に熱いビジョンを秘めてる。\n・「それ、なんでそうなるか分かってた」って顔してるタイプ。\n・無駄が嫌い。効率の鬼。by ChatGPT診断",
                "## 👤名前 　： きょへ\n## 🛠️スキル ： 前置きなく急にVCに現れる(？)\n## 🧪特性 　： 突然呪われたかのように表れ、何かの検証を始め、満足して帰っていく。\n## 📝注意 　： 突然やる気を失うので定期的にけつを叩いて下さい。",
                "このBotを作り上げた圧倒的天才！\n出来る事はピアノ、体操、バドミントン、他運動、書道、ゲーム、動画編集、BOT作り、検証、数学………。と多岐にわたる。\nあまりにも多彩で出来ない事は基本存在しないとも言われている…！\nこのBOTもその天才に作られており、どこにもミスや誤字などは無い。\nそのIQはなんと175cmにも及ぶと世間で噂されている。"],
    type: "random"
  },
  { pattern: /きょへ。?さんは/,
    responses: ["やあ！",
                "きょへさんに何か用かい？\nメンションすると良いよ。\n彼は暇人だからね。",
                "代わりにメンションしてほしいって？\nいいよ！<@530155393117192203>",
                "お呼び出しだ。\nさっさと来い<@530155393117192203>",
                "なんでしょうか！\n火種の事ならK-botにメンションして聞いてくれれば答えるよ！✨",
                "よばれて飛び出てジャジャジャジャーン♪！！\n・・・\n・・・早く来い。\n<@530155393117192203><@530155393117192203><@530155393117192203><@530155393117192203><@530155393117192203><@530155393117192203>"],
    type: "random"
  },
  { pattern: /月は|つきは|ツキは/,
    responses: ["このサーバー初の韓国系ゲーマー！",
                "最近エアレを始めて期待値大！",
                "なんと…韓国語が読める！！",
                "きょへとクマに挟まれたエアレ勢",
                "ゲーム大好き"
    ],type: "random"
  },
  { pattern: /志麻は|しまは/,
    responses: ["いつも眠い人",
                "ツボが浅くてなんでも笑うコスパ良い系男子(違う)",
                "# ごめんなさいのポーズ\nと言うと泣いて喜ぶよ！",
                "そろそろ最上位勢になってくれる兆しが足元に差し込みそうなエアレ勢！",
                "https://cdn.discordapp.com/attachments/1474742738787242185/1491370629956636794/30s.mp3?ex=69d772a2&is=69d62122&hm=02420a2c1f0ab003d75554f2f123945d29f77dfe6c10051d546f3af310be102a&",
                "合奏に手を出そうとしたものの、一緒に参加する予定だった人が寝落ちて断念。"
    ],type: "random"
  },
  { pattern: /へこにゃんは/,
    responses: [
      "百合好きの76才！！なんと現役JK！！！",
      "たまに真面目なこと言うけど9割は適当",
      "最前線で社会の理不尽さを嘆くピカチュウ使い",
      "もともとは高貴なゲッコウガ使いだった。",
      "# さすへこ！\nと言うと喜ぶよ！",
      "女の子からｶﾜｲｸお願いすれば、カラオケ配信してくれます！",
      "たまに自転車に乗ってると車に轢かれる可哀そうな子！ｱﾗﾔﾀﾞ",
      "全世界に愛されし現役バ美肉女子高生(76)"
    ], type: "random"
  },
  { pattern: /スニャイヴは/,
    responses: [
      "Xでは控えめなくせに。この鯖になったら…変人。\nbyおれ！",
      "# BOTはよアップグレードしてくれ！\nbyおれ！",
      "プログラムの事はこいつに聞けば3％は分かる！！\nbyおれ！",
      "skyでは怠惰厨\nbyおれ！",
      "スマブラでは空後空後空後空後空後……!!!!\nといった感じで空前絶後の擦り厨。\nbyおれ！",
      "デジタル環境への不満: YouTubeの再生履歴やWindowsアップデートの挙動にストレスを感じていると投稿しており、デジタルツールの使い勝手に敏感で、改善を求める一面も見られます。\nby Grock",
      "スニャイヴさんは、ツタージャへのガチ愛とゆる〜い雑学ノリ\nそしてちょっとした計算ネタを交えた独特のつぶやきスタイルで個性を出しています。\nストレートに好きなものを表現し、人を選ぶかもしれませんが、ハマった人にはクセになるアカウント✨\nby ChatGPT",
      "ツタージャLove♡\nポケモン「ツタージャ」を愛してやまない熱量がバイオににじみ出ています。\n好きなキャラクターをストレートに推すタイプですね。\nby K-botAI",
      "# 🧠一言でいうと？\nツタージャへの愛をこじらせた、理系っぽいポケ廃。\nでもたぶん理系じゃない。気持ちだけ。\nby ChatGPT",
      "🔥こんな人にオススメ\nX（旧Twitter）で「何言ってんの？」って笑いたい人\nby Gemini",
      "発言はゆるゆる、たまにガチっぽい理論展開してくるから油断ならない。\nツタージャの布教活動中。たまに事故る。\nby Gemini"
    ], type: "random"
  },
  { pattern: /たっつんは/,
    responses: [
      "⠀　　    ゆ\n⠀　  あ  で\n⠀ゆ  あ  た\n⠀で  ゆ  ま\n⠀た  で  ご\n⠀ま  た\n⠀ご  ま\n⠀　  ご",
      "# 圧倒的コミュ強。\nそのコミュ強を武器にあらゆる人との繋がりを持っている。\n-# ただし頭皮と毛の繋がりはない模様。",
      "声がでかくて、風呂が長い！\nハゲ！と呼びかけると元気に答えてくれる本能を持ち合わせている",
      "いつでもどこでもヒトカラ配信してくれ~る！やっさしぃ存在！キャー！！",
      "声デカいから鼓膜破損には注意してね。",
      "鼓膜には注意してね。",
      "たっつんと言えば、ウィーアー歌ってみた！だと思うんだ！俺は！\nhttps://youtu.be/oz66sH_62OE?si=v06lm3j3IpB74g_P",
      "負けた時とか言い訳しやがる！\n他責思考すんな！お前の責はお前が持て！\nそれが成長に！\nﾝｱｯ\n# つながぁああ～～～っる！！",
      "おじさん/おっさん と呼ぶと脊髄反射で||「〇〇～‥‥」||と答えてくれる。\nその答えは君の眼で確かめるのだ！"
    ], type: "random"
  },
  { pattern: /うみは/,
    responses: [
      "うみばよ!!",
      "英語達者、日本語達者、母国語の広東語、そして中国語……\nどういう脳みそしてたらそんな覚えれるんだろうね？？？？",
      "発言、声ともに可愛さ100点満点！",
      "くしゃみの仕方が異常にかわいい。おかしい。さすがにおかしい。",
      "# バヨバヨ\nとたまに言う謎の子。\n取材班が彼女に意味を聞いた所、「バヨバヨはバヨバヨだよ」との事。",
      "謎多き女の子。彼女を理解できる日は我々に来るのだろうか…。",
      "APEX好きなワサビ創設者",
      "APEX好きなワサビ創設者"
    ], type: "random"
  },
  { pattern: /だめえみ/,
    responses: [
      "https://cdn.discordapp.com/attachments/930348999645483111/1438161970980454501/Screenshot_20251112-224140_LINE_1.jpg?ex=6915e035&is=69148eb5&hm=3131257af45a8b775a2fa578660176661518c2cb8f0f831b98751af4917d078c&",
      "https://cdn.discordapp.com/attachments/930348999645483111/1438166161815769148/59583d083e13628e.jpg?ex=6915e41c&is=6914929c&hm=d2cd639a5ea59f3ef41671c449a546bbda741b6831fcccbee66d4ec68ad1f9a5&",
      "https://cdn.discordapp.com/attachments/930348999645483111/1438162472140804096/Screenshot_20251112-224340_LINE_1.jpg?ex=6915e0ad&is=69148f2d&hm=3fff76d0fb27a72f9af51d0f9900a14a9d61c044a2705983a2055022afc9d2aa&",
      "https://cdn.discordapp.com/attachments/930348999645483111/1438161880249143386/Screenshot_20251010-232357_LINE_1.jpg?ex=6915e020&is=69148ea0&hm=08598e94699a8b6a93670cc06080f8a6cde6d5f9896c446f6c989953430be148&"
    ], type: "random"
  },
  { pattern: /たまちゃんは|たまっぴは/,
    responses: [
      "# めんこ～～～いッ‼‼‼",
      "たまにパソコンぶっ壊してるお茶目な子",
      "はざまの前では脳の機能が低下し、\n一時的なIQは3との噂も巷では…。",
      "自分なりに追及したり質問したり、固定概念なく人の言葉を素直に信じられる子",
      "行動力とフットワークの軽さが魅力。ありがたい",
      "手先が器用でハンドメイド作品を多数出展しているらしい！",
      "# ナダル・ボンジョルノ\nというと喜ぶよ！",
      "たまちゃんの姉は、タマネキ\nたまちゃんの妹は、タマイモ\nと呼ばれている。\n-# ｵｲｼｿｳ",
      "行動力はちゃんとあって、やる時はやる。コツコツやる力もある"
    ], type: "random"
  },
  { pattern: /あっとるは/,
    responses: [
      "裏世界探索のプロ!!",
      "知らん裏世界を日に日に見つけている気がする。",
      "グリッチ職人に片足突っ込んでる気がする"
    ], type: "random"
  },
  { pattern: /かえは/,
    responses: [
      "探求心、追求心が高くて沢山質問してくるので今後もっと成長する！",
      "たまに変な発言してくるけど、知識に対する貪欲さ故のものかな。と。",
      "「なぜ？」「どうして？」を自然に聞ける子。深く考えるのが好きだったりするのかな？",
      "質問数＝知識量に変換する最強タイプ",
      "レコキャンワープの最前線にいるプレイヤーではなかろうか。",
      "・人の心を大切にするタイプ。\n・感情に素直で、でも押しつけない。控えめだけど芯がある",
      "何事も深掘りするから、成長速度がえぐい"
    ], type: "random"
  },
  { pattern: /Hiroは|Hiro母さんは/,
    responses: [
      "時々抜けてる…ｗ",
      "しれっと核心を突いてくるお母さん枠"
    ], type: "random"
  },
  { pattern: /こんは|こんにゃくは|konnyakuは/,
    responses: [
      "語学力高すぎて時々AIかと思ってしまいます。by BOT",
      "If you're not a fun guy, she's not interested.\n-# …キノコ好きなこんさんだけにね",
      "キノコ大好きすぎてキノコ博士。\nキノコの事は彼女に聞けば間違いない。ベニテングダケ振る舞ってください♪",
      "モンハンプレイしたら真っ先に「キノコ大好き」のスキルを最大にする気がする。",
      "フッ軽すぎて色んな所に行くアクティブさが尊敬レベル。",
      "たまにこんさんが日本人じゃない事に違和感を感じる瞬間があるくらいには日本語が上手すぎる。\n……いや、日本語第3言語らしいですが…？？？？？？？？？",
      "意外と理論的思考が多く、きょへ。という私を作ったユーザと思考は似てるが、\nその後の行動パターンはきょへと異なっているように見受けられます。\n　\nﾆﾝｹﾞﾝって面白いﾃﾞｽﾈ。"
    ], type: "random"
  },
  { pattern: /ことは/,
    responses: [
      "「小兎は」で打てばちゃんと出るよ"
    ], type: "random"
  },
  { pattern: /小兎は/,
    responses: [
      "ぱっと見では消極的のように見えるかもしれないけど意外と頼もしく、何でも自分でこなそうとする実は芯の強い子。",
      "言葉の本質を深く捉える性格…かな？故に考え過ぎてショートしてしまう特性があるけど基本は人の意見を尊重してる",
      "純粋な心を持ってて大事なものは最優先に、やりたい事はしっかり努力してやるタイプ",
      "多分本人は自覚ないけど普通にゲームが上手い！",
      "ウサギが大好きな兎博士！\nウサギの事を聞けば大抵は答えてくれるよ！",
      "歴史が好きらしい。K-Botは歴史苦手。年号ムリ。",
      "この鯖のイベントチャンネルに定期的にイベントを貼ってくれるすごくありがたい存在",
      "薄ピンクが好きな可愛い系女の子！\n白の判定には厳しい。\n彼女曰く、マイクラの白いコンクリートは白くないらしい…。\n-# いや…白いやん…？",
      "シェアスぺ作るのがとっても上手！！"
    ], type: "random"
  },
  { pattern: /こまは/,
    responses: [
      "美容室に行ってswitchを買う子（???????）"
    ], type: "random"
  },
  { pattern: /しぃちゃんは/,
    responses: [
      "こんドロの紅一点",
      "たまに出る癒しボイスで視聴者のやる気を底上げする存在",
      "意外と芯が強くて意見ははっきり言える所がカッコいい",
      "ゲームは勝ち負け系の結果より楽しむ事や過程が好きなタイプ！",
      "リクエストしたらお姉さんボイスで答えてくれるかも！",
      "スマブラではルキナを使ってる！",
      "K-Botの生みの親にskyというゲームを進めた2人のうちの1人",
      "ゲームは勝ち負け系の結果より楽しむ事や過程が好きなタイプ！",
      "裏番長説…濃厚…。\n-# （諸説あり）"
    ], type: "random"
  },
  { pattern: /ふゆさくらは/,
    responses: [
      "イケボぶっぱ厨",
      "強い思いがあって人と対立する事もあるけど曲がらない強さがある",
      "# 実は！！\nお料理の事に詳しいのよ！",
      "スマブラでは上位プレイヤーを破壊力を持ってる。\n-# ただし待ち戦法、ガーキャン戦法にはめっきり弱い…ｗ\n-# 彼にとって待ちやガードは漢の所業ではないとか…。",
      "のめりこんだものにはえぐい集中力、探求力がある恐ろしい人"
    ], type: "random"
  },
  { pattern: /くらげは|海月は/,
    responses: [
      "魑魅魍魎ちゃんがどうしたって？",
      "存在が深海生物レベルで未知",
      "優しくて素直で良い子。フラッとあらわれてふらっと消える。\n…波に流されてます？ｗ"
    ], type: "random"
  },
  { pattern: /てんちゃんは/,
    responses: [
      "この鯖の声かわ代表",
      "天然ボケをかましてくれるありがたい存在ｗ",
      "人が楽しそうだから～という理由で色んなことをやってみる行動力がある",
      "アイドル的ポジション（非公式）"
    ], type: "random"
  },
  { pattern: /まりむーは/,
    responses: [
      "弊社の癒し担当です",
      "静かに現れて静かに癒してく",
      "声が合法睡眠薬。寝ないんですか～？"
    ], type: "random"
  },
  { pattern: /こーやは/,
    responses: [
      "最近みませんね",
      "いるようでいない、いないようでいる",
      "実は裏で全部見てるタイプかも…！"
    ], type: "random"
  },
  { pattern: /ワドやんは/,
    responses: [
      "僕の鯖のやばいヤツ",
      "最近本当に見なくなったな…"
    ], type: "random"
  },
  { pattern: /ズーマーは|ズマは/,
    responses: [
      "ロリコンコンコンです",
      "「ずぅまぁふけんこうからださん」それが彼の本名です。",
      "白い耳がある、ネコみたいなキャラ、「白上フブキ」って子が推しらしいよ！けもなーなのかな？",
      "ゴーヤって言ったら怒るかも",
      "琉球王国に住んでいます",
      "うみちゃん曰く、「ズマの髪もふもふだよ！！」との事。",
      "# ズマ\nなんかおもろくない？ｗ",
      "カラオケバイトからカラオケの店長に。そして今はホテルで働いている。働いた金は全てVtuberに貢いでいるとか…いないとか…。",
      "もうズマって単語だけで笑えるｗｗｗ\nなんでなんだろね？"
    ], type: "random"
  },
  { pattern: /ゆなしばは/,
    responses: [
      "あんまよく分かってないｗ"
    ], type: "random"
  },
  { pattern: /ばんちょは/,
    responses: [
      "Sky知識豊富　キャリー上手い。こんばんちょ。",
      "sky一緒にやると安心感がすごい"
    ], type: "random"
  },
  { pattern: /emicは|emic.は|えみっくは|エミックは|えみたろは/,
    responses: [
      "相手に合わせて自分を変えるのが上手。苦手な人でもうまくやっていける社交性や愛嬌あり。少々お人好しで、頼まれたら断れなく、困っている人は放っておけない。人に尽くすのが好き。誰かが喜ぶなら、つい自分が損をしてでも奉仕してしまう。平和主義な一面もあり、衝突を避けるためなら自分が折れることも多いはず。また、とても積極的で何をするにもチャレンジ精神旺盛に取り組む。挑戦する度に知識や経験を吸収していき、必要な時に活かすことができる。しっかり者のようで案外抜けたところもある天然タイプです。",
      "・静かで思慮深い理想主義者\n・相手の気持ちをすぐ察知する優しい子\n・ひとりの時間も好きだけど、誰かの力になれる瞬間に生きがいを感じるタイプ\n・表には出さないけど内側でめちゃくちゃ燃えてる",
      "ｳﾝﾁｨｰ!!!!",
      "# たっくあぁ～～～ん！♡",
      "# 知る人が知る\nbyえみたろ 2025.11.12",
      "https://cdn.discordapp.com/attachments/930348999645483111/1438160832159809678/51EoiabJfZL._AC_UF8941000_QL80_.jpg?ex=6915df26&is=69148da6&hm=828f4cb437de20ad4a86bea97b7f0b0a82b7ef01ed661989293fe8b7320f30f6&\nhttps://cdn.discordapp.com/attachments/930348999645483111/1438160832776241152/donpenProf03-770x530.png?ex=6915df26&is=69148da6&hm=027219d58bc0521fd88dc996b5728640a60ff5b08043e53be336038400b761b1&\n# ⇩これ、瞳の大きさが違うんだね\nbyえみたろ 2025.11.12",
      "たくあんでも食ってろ！！",
      "熱血☆麦チョコ☆アックス！\nhttps://cdn.discordapp.com/attachments/1156942637799059567/1360851281324802270/56BE8526-EF11-4D28-B0AA-38F29BAF9401.png?ex=6854f384&is=6853a204&hm=b58c1ce43fade4eee02255ffea7d725ce3b18df0e741ce2d5be3df60045b248a&",
      "2025年6月20日の名言「ここは変態ばっかりな人だな(？)」by えみたろ。",
      "ちゃんとして！！！！！！！！！",
      "ｷｬﾜｷｬﾜｷｬﾜさどちゃあああああん🤤🤍🤤🤍🤤🤍\nと、いつもよだれを垂らしています",
      "# たっくよぉ～～\nが好きな変わった女の子。たっくよぉ～が進化してたっくあ～んと呼ばれた暁には彼女に認められたという事で一人前になれたという文化があるとか…ﾅｲﾄｶ…"
    ], type: "random"
  },
  { pattern: /ハゲは/,
    responses: [
      "たっつんだよ。",
      "誰がハゲやねん by ~~はげ~~たっつん",
      "もはやアイデンちちぃ\nーー  by たっつん  －－"
    ], type: "random"
  },
  { pattern: /タカ氏は/,
    responses: [
      "優しい　穏やか　優しい　頭がいい　優しい　上手い　安い　早い　牛丼好き。ｼﾗﾝｹﾄﾞ",
      "やたら優しさが多め",
      "オフ勢のピカ使い。京都の人なのでお風情が感じられます",
      "スマブラでたまにえぐい読みを通してくるのが怖い。基本かたくリスク減らして立ち回る系"
    ], type: "random"
  },
  { pattern: /ルイは|るいは/,
    responses: [
      "オチリが好きな変態さん",
      "変態を隠さないタイプの変態",
      "好きなものに正直な人生、見習いたい",
      "るい＝オチリ、までが定義"
    ], type: "random"
  },
  { pattern: /ロンは|ろんは/,
    responses: [
      "僕ッ子",
      "実はめっちゃモテる説濃厚"
    ], type: "random"
  },
  { pattern: /みぃは/,
    responses: [
      "skyの圧倒的知識の持ち主。キャンマラの先駆者",
      "エアレでもしっかり知識と発想力を使って名を残している",
      "この人がいれば道に迷わない",
      "またキャンマラしてください！",
      "sky博士（非公認）"
    ], type: "random"
  },
  { pattern: /unknownは|unknöwnは/,
    responses: [
      "自分で打つな",
      "名前はまだないらしい。本名も。"
    ], type: "random"
  },
  { pattern: /unkonowは/,
    responses: [
      "いやそれ誤字ってう〇こナウになってるやんｗ",
      "変換事故で笑い取ってくタイプ",
      "狙ってなくても面白いのは才能",
      "多分それえみちゃんが喜ぶ誤字。"
    ], type: "random"
  },
  { pattern: /フィルは/,
    responses: [
      "よく知りません",
      "それ以上でもそれ以下でもないよく分からない人。"
    ], type: "random"
  },
  { pattern: /スニャイブ/,
    responses: [
      "スニャイブ じゃなくて スニャイ ヴ ですよ？ねえ？スニャイブ君？",
      "エゴサ全1。誤字される率も全1。"
    ], type: "random"
  },
  { pattern: /くみちょうは/,
    responses: [
      "スマブラ頑張っててえらいといつも思ってます。いやマジで",
      "たまに助けを求めに来る姿勢、受け止める姿勢はカッコいい",
      "ゲームに本気な大人はかっこいい"
    ], type: "random"
  },
  {
    pattern: /さーどちゃん|サードちゃん|さどちゃん|サドちゃん/,
    responses: [
      "https://cdn.discordapp.com/attachments/1022093564995436594/1217037624385212436/3rd_slow.mp4",
      "きょへの第3の子。よく勘違いされるが、3垢目ではなく4垢目。"
    ], type: "random"
  },
  {
    pattern: /のわゆは/,
    responses: [
      "最近ログインしてるの見ないカモ",
      "まだ息してる…？（失礼）",
      "逆に今どこにいるか気になる系存在"
    ], type: "random"
  },
  {
    pattern: /さすへこ/,
    responses: [
      "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/%E3%81%95%E3%81%99%E3%81%B8%E3%81%93PNG.jpeg?v=1740915170843",
      "さすが我らがへこにゃん様！！！！",
      "カッコいいすごいｷｬｰ!!!!",
      "たまに画像付きで煽られるタイプ"
    ], type: "random"
  },
  {
    pattern: /ななしは/,
    responses: [
      "お風呂RTA世界記録保持者",
      "アカウントはもう消えました。",
      "私はなぜか恨まれてるらしいです。なんで？",
      "風呂の妖精"
    ], type: "random"
  },
  {
    pattern: /一縷は/,
    responses: [
      "なにわをてんねん！の生みの親…だったような気がしてる",
      "最近は彼女が出来てにやにやしてます。",
      "あの偉大ないちるまいちるチルトリスチャンネル創設者。",
      "ピカチュウ(スマブラではなく)の知識と愛が異常にある。怖い。昔それで引かれてたらしいです。ｶﾜｲｿｳﾆ。"
    ], type: "random"
  },
  
  {
    pattern: /くまは/,
    responses: [
      "グリッチのスペシャリスト。そしてSNS発火のプロ…ｗ",
      "skyのグリッチや試練の最先端である中国系の情報に強くてとても助かる",
      "発想力と経験値が豊富で且つ柔軟なので色んな視野からグリッチに対する観点、開発視点を持てている。",
      "兄の名はくまごろう。弟の名前はくまいちろう。じゃあ、彼の名は…？"
    ], type: "random"
  },
  
  {
    pattern: /ぽにーたは|ポニータは|氏ポニータは/,
    responses: [
      "# ぽにぃたまぁぁ～～～！\nな人。",
      "若く素直。とても良い。伸びしろたっぷり",
      "名前の由来は何なんだろうね",
      "スマブラ勢、リドリー使い。撃墜体でＤＡしない。崖を狩らない。ありがとう。しゅき！あ。でも崖上がり横Ｂしてくる。嫌い。"
    ], type: "random"
  },
  {
    pattern: /しんどい|疲れた|つかれた|疲れました|つかれました|死にたい|しにたい/,
    responses: [
       ["https://twitter.com/purinharumaki/status/1236262228581466112?s=20&t=Bg1hXcIolEEil7_xlZLR5w", "これ見て笑えよ"],
       ["https://twitter.com/BornAKang/status/1574125489110728705?s=20&t=WDmSSyUE4Rm50mU-staUaQ", "これ見て笑えよ"],
       ["https://twitter.com/aoihk_118/status/1561345302120271872?s=20&t=WDmSSyUE4Rm50mU-staUaQ", "これ見て笑えよ"],
       ["https://twitter.com/shouldhaveaduck/status/1574819532052766720?s=20&t=k3C0Dl0NG8mbtwaiK5K5oA", "これ見て笑えよ"],
       ["https://twitter.com/purinharumaki/status/1236262228581466112?s=20&t=WDmSSyUE4Rm50mU-staUaQ", "これ見て笑えよ"],
       ["https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/XiaoYing_Video_1468200848374.mp4?v=1702753816734", "これ見て笑えよ"],
       ["https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/RPReplay_Final1656442030.mov?v=1702753818389", "これ見て笑えよ"],
       ["https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/trim.EC1B9271-A86A-4BCE-BD4F-3AA97650813C.mov?v=1702753819841", "これ見て笑えよ"],
       ["https://www.youtube.com/watch?v=XlEo9sjLEs8&list=LL&index=5", "これ見て笑えよ"],
       ["https://www.youtube.com/watch?v=YTwK96HddCo&list=LL&index=6", "これ見て笑えよ"],
       //["ねえねねえええ", "これ見て笑えよ"],
       //["ねえねねえええ", "これ見て笑えよ"],
       ["https://youtu.be/xQ-A48PItOU?si=Wa-ElGAoVALdpTDP", "これ見て笑えよ"],
       ["https://youtu.be/QPvXp_OGaSg?si=wRsffTDHfBKtU6Na", "これ見て笑えよ"],
       ["https://youtu.be/rPvcGSIZmfI?si=In-dz3rWsHNk9bAo", "これ見て笑えよ"],
       ["https://youtu.be/GKc7pVQOYYg?si=LrAjUzA5Ofxd97Fq", "これ見て笑えよ"],
       ["https://youtu.be/9V2LwgdGia0?si=7EwvfALS_NA1PX1y", "これ見て笑えよ"],
       ["https://youtu.be/OyX7lh0Fq1Y?si=dhhRbt4d50iOGKmA", "これ見て笑えよ"],
       ["https://x.com/agashiagashi/status/1917209037118325166", "これ見て笑えよ"],
       ["https://www.youtube.com/watch?v=ZpsG36Du8_E&list=LL&index=7", "これ見て笑えよ"],
       ["https://youtu.be/E_mW_Aj5qCY?si=2QeSkkAZnpwLW85L", "これ見て笑えよ"]
    ], type: "random"
  },
  { pattern: /ケーボット|けーぼっと|K-?bot/i, 
    responses: [
      "はいはーい！メンションしてくれれば最新AIが返事するよ！",
      "お金を入れてね！カードが貰えるよ！"
    ], type: "static" },
  { pattern: /うえからみたっつん|上からみたっつん|上から見たっつん|うえから見たっつん/,
    responses: [
      "https://cdn.discordapp.com/attachments/1007569901457780827/1066748844974555256/7e761eb540b3d144.mp4",
      "https://cdn.discordapp.com/attachments/1007569901457780827/1066748925719105578/402b6a73c6da4df7.mp4",
      "https://cdn.discordapp.com/attachments/1007569901457780827/1066748961689440326/127f3ecd5b797dcc.mp4",
      "https://cdn.discordapp.com/attachments/1072643515248549968/1183499885736104047/c8821e1e8e87b669.mp4",
      "https://cdn.discordapp.com/attachments/1072643515248549968/1183499179989938247/1.mp4?",
      "https://cdn.discordapp.com/attachments/1007569901457780827/1066750192747028530/e0cb6e42fac93ce7.mp4"
    ], type: "random"
  },
  { pattern: /ｓぁｆじゃｋｌ/,
    responses: [
      "1",
      "2",
      "3",
      "4"
    ], type: "random"
  },

  //おみくじ
  {
  pattern: /！おみくじ|!おみくじ|おみくじ/,
  responses: [
    { texts: ["🎊すっごーーーい大吉！！🎊", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/%E3%81%8A%E3%82%81%E3%81%A7%E3%81%A8%E3%81%86-%E5%AC%89%E3%81%97%E3%81%84.gif?v=1677096667773"],weight: 6 },
    { texts:["✨✨かなり大吉✨✨", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/%E3%81%8A%E3%82%81%E3%81%A7%E3%81%A8%E3%81%86-%E5%AC%89%E3%81%97%E3%81%84%20(1).gif?v=1677096670342"],weight: 9 },
    { texts:["✨吉だね！✨", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/5c1d0bec96c0080c863ce98c199066dc.gif?v=1677098206251"],weight: 12 },
    { texts:["中吉だなぁ～👍", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/%E3%81%99%E3%81%94%E3%81%84-%E6%8B%8D%E6%89%8B.gif?v=1677096665281"],weight: 15 },
    { texts:["凶！", "https://cdn.discordapp.com/attachments/932595932464291872/1078024865031913543/b23a176962cdbe5b.gif"],weight: 9 },
    { texts:["大凶。背後には気を付けろよ・・・。", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/%EF%BC%91%EF%BC%92%EF%BC%93.gif?v=1677098585621"],weight: 6 },
    { texts:["きょへ様を崇めよ", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/o0365019912329969675.gif?v=1677096910953"],weight: 4 },
    { texts:["たっつんは泳いでいます。ここで", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/people_0008_pool.gif?v=1677096924065"],weight: 1 }
  ],  type: "weighted"
  },
  { pattern: /ｓぁｆじゃｋｌ/,
    responses: [
      "1",
      "2",
      "3",
      "4"
    ], type: "random"
  },
  
  // static ＝ シンプル処理
  { pattern: /たっつんは/,
    responses: ["👇これがたっつんの実際の映像です👇",
                "https://zukan.pokemon.co.jp/zukan-api/up/images/index/596b399e3c5786fc8bf8856adf3f7cf5.png"
               ],
    type: "static"
  },
  { pattern: /先行入力は/,
    responses: ["1.通常の先行入力：次の動作が可能になる９F前までに入力されたアクション\n2.押しっぱなし先行入力：次の動作が可能になる3F前までホールドされたアクション"],
    type: "static"
  },
  { pattern: /反転空後のコツは/,
    responses: ["兎にも角にも練習練習練習"],
    type: "static"
  },
  { pattern: /空ダのコツは/,
    responses: ["この動画がオススメ！",
               "https://youtu.be/4JAx3ZkWPfs"],
    type: "static"
  },

  //ピカチュウ系　static
  { pattern: /ピカチュウは/, responses: ["かわいい"], type: "static" },
  { pattern: /ピカチュウの弱|ピカの弱/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuJab.gif", "判定：2~3F 全体：17F 不利：12~13F"], type: "static" },
  { pattern: /ピカチュウの横強上|ピカの横強上/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFTiltUp.gif", "判定：6~8F 全体：29F 不利：13F（上シフト）"], type: "static" },
  { pattern: /ピカチュウの横強下|ピカの横強下/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFTiltDown.gif", "判定：6~8F 全体：29F 不利：15F（下シフト）"], type: "static" },
  { pattern: /ピカ(チュウ)の横強|ピカの横強/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFTilt.gif", "判定：6~8F 全体：29F 不利：14F（無シフト）"], type: "static" },
  { pattern: /ピカチュウの上強|ピカの上強/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuUTilt.gif", "判定：7~13F 全体：26F 不利：13F(背面) / 7~10F（正面）"], type: "static" },
  { pattern: /ピカチュウの下強|ピカの下強/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDTilt.gif", "判定：7~8F 全体：18F 不利4F ←つまりガーキャン空中攻撃はまず不可能"], type: "static" },
  { pattern: /ピカチュウのDA|ピカのDA|ピカチュウのダッシュアタック|ピカのダッシュアタック|ピカチュウのda|ピカのda/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDashAttack.gif", "判定：6~8/9~12F 全体：35F 不利：11F"], type: "static" },
  { pattern: /ピカチュウの横スマ|ピカの横スマ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFSmash.gif", "判定：15~16/17~19(SS)/20~29F 全体：53F 不利：27/24/~24F 全然飛ばない"], type: "static" },
  { pattern: /ピカチュウの上スマ|ピカの上スマ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuUSmash.gif", "判定：10~12/13~14/15~17F 全体：44F 不利：24F ガーキャン掴みより早いヨ"], type: "static" },
  { pattern: /ピカチュウの下スマ|ピカの下スマ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDSmash.gif", "判定：8~9/11~12/14~15/17~18/20~21/23F 全体：65F 不利：39F 弱すぎｗ"], type: "static" },
  { pattern: /ピカチュウのダッシュ掴み|ピカのダッシュ掴み/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDashGrab.gif", "判定：11~12F 全体：44F"], type: "static" },
  { pattern: /ピカチュウの振り向き掴み|ピカの振り向き掴み|ピカチュウのふりむき掴み|ピカのふりむき掴み/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuPivotGrab.gif", "判定：12~13F 全体：39F"], type: "static" },
  { pattern: /ピカチュウの掴み打撃|ピカの掴み打撃|ピカチュウの掴み攻撃|ピカの掴み攻撃/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuPummel.gif", "判定：1F 全体：5F"], type: "static" },
  { pattern: /ピカチュウの掴み|ピカの掴み|ピカチュウのその場掴み|ピカのその場掴み/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuGrab.gif", "判定：7~8F 全体：36F"], type: "static" },
  { pattern: /ピカチュウの空前|ピカの空前/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFAir.gif", "判定：11~25(Rehit:3)/27F 全体：41F 着地隙：12F 不利：9~12F(降り) or 12F(sj最速急降下無し) or 7F(sj最速+24F目で急降下 or sjしてから8F目で出す)"], type: "static" },
  { pattern: /ピカチュウの空後|ピカの空後/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuBAir.gif", "https://ultimateframedata.com/hitboxes/pikachu/PikachuBAirLanding.gif", "判定：4~5/8~9/12~13/16~17/20~21/24~25/1~2(LF)F　全体：43F　着地隙：(LF)18F　不利：12F(降り)   or   16F(sj最速+急降下無し)   or   15F(sj最速+36F目に急降下)   or   12F(sj最速+最速急降下)"], type: "static" },
  { pattern: /ピカチュウの空上|ピカの空上/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuUAir.gif", "判定：4~6/7~8F　全体：26F　着地隙：14F　不利：11~約20F(降り)   or   19F(sj最速)   or   14F(sjしてから22F目で出す：本当て)   or   11F(sjしてから22F目で出す：カス当て)"], type: "static" },
  { pattern: /ピカチュウの空下|ピカの空下/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDAir.gif", "https://ultimateframedata.com/hitboxes/pikachu/PikachuDAirLanding.gif", "判定：14~15/16~26/1~2F　全体：47F　着地隙：(LF)22F　不利：16F(降り)   or   23F(sj最速)     ※(sj最速+最速急降下によるLFまでの間の不利は7F)"], type: "static" },
  { pattern: /ピカチュウのNB|ピカのNB|ピカチュウのnb|ピカのnb/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuThunderjoltAerial.gif", "判定18~52(最短)：F　全体：74(最短) / 21(衝突後)F 不利：2~15F"], type: "static" },
  { pattern: /ピカチュウの空N|ピカの空N/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuNAir.gif", "判定：3~6/9~12/15~18/21~22F　全体：38F　着地隙：9F　不利：7~12F(降り)   or   19F(sj最速)   or   13~18F(sj最速+急降下)"], type: "static" },
  { pattern: /ピカチュウの横B|ピカの横B|ピカチュウの横b|ピカの横b/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuSkullBash.gif", "判定18~52(最短)：F　全体：74(最短) / 21(衝突後)F 不利：2~15F"], type: "static" },
  { pattern: /ピカチュウの上B|ピカの上B|ピカチュウの上b|ピカの上b|ピカチュウの石火|ピカの石火|ピカチュウの電光|ピカの電光/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuQuickAttack.gif", "判定：15~19/29~33F　全体：(43)/(57)F　着地隙：24F　不利：21~34(１段目) / 20~24(２段目着地)F"], type: "static" },
  { pattern: /ピカチュウの下B|ピカの下B|ピカチュウの下b|ピカの下b|ピカチュウの雷|ピカの雷|ピカチュウのかみなり|ピカのかみなり/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuThunder.gif", "https://ultimateframedata.com/hitboxes/pikachu/PikachuThunderHit.gif", "判定：13~15/21~23(稲妻) / 16~85/24~93(稲妻持続)F　全体：86(未接触) / 41(接触：地上) / 35(接触：空中)F　全身無敵：1~10(接触：地上) / 1~8(接触：空中)　不利：26(地上) / 20(空中)F"], type: "static" },
  { pattern: /ピカチュウの前投げ|ピカの前投げ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuFThrow.gif", "判定：11/15/19/23/30F　全体：45F"], type: "static" },
  { pattern: /ピカチュウの下投げ|ピカの下投げ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuDThrow.gif", "判定：29F　全体：51F"], type: "static" },
  { pattern: /ピカチュウの上投げ|ピカの上投げ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuUThrow.gif", "判定：14/16F　全体：35F"], type: "static" },
  { pattern: /ピカチュウの後ろ投げ|ピカの後ろ投げ/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/PikachuBThrow.gif", "判定：26 全体：49F"], type: "static" },
  { pattern: /ピカチュウの攻撃あがり|ピカの攻撃あがり|ピカチュウの攻撃上がり|ピカの攻撃上がり/, responses: ["https://ultimateframedata.com/hitboxes/pikachu/pikachuGetupAttackU.gif", "https://ultimateframedata.com/hitboxes/pikachu/pikachuGetupAttackD.gif", "https://ultimateframedata.com/hitboxes/pikachu/pikachuTripAttack.gif", "https://ultimateframedata.com/hitboxes/pikachu/pikachuLedgeAttack.gif"], type: "static" },
  { pattern: /ピカチュウの崖掴み|ピカの崖掴み/, responses: ["https://ultimateframedata.com/ledgegrabs/Pikachu%20Ledgegrab%201.png", "https://ultimateframedata.com/ledgehangs/PikachuLedgehang.gif"], type: "static" },
  { pattern: /ピカチュウのステータス|ピカのステータス|ピカチュウの体重|ピカの体重|ピカチュウの重さ|ピカの重さ/, responses: ["体重：79(79位)　歩行速度：1.302(13位)　走行速度：2.039(20位)　空中速度：0.957(66位)　走行移行前F 12(73位)　落下速度：1.55(53位)　急降下速度：2.48(51位)"], type: "static" },

  //きょへ系 static
  { pattern: /きょへ。?の原罪マップ|きょへ。?原罪マップ|きょへ。?さんの原罪マップ/, responses: ["https://youtu.be/Ew921TnFoaw?si=Ic79rsavyEZPTokJ", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/kyoheVer.jpg?v=1683557962502"], type: "static" },
  { pattern: /きょへ。?の性癖|きょへ。?さんの性癖/, responses: ["https://cdn.discordapp.com/attachments/932594717529604116/1022114482878685264/IMG_5258.png"], type: "static" },
  { pattern: /きょへ。?の年収|きょへ。?さんの年収/, responses: ["年収なんと2億!!おめでとうございます！ありがとうございます！"], type: "static" },
  { pattern: /きょへ。?の月収|きょへ。?さんの月収/, responses: ["月収なんと0.2万円!!"], type: "static" },
  { pattern: /きょへ。?の日給|きょへ。?さんの日給/, responses: ["日給はなんともやし7袋!!"], type: "static" },
  { pattern: /おい！きょへ！/, responses: ["Yeah Ｉ'm boring man..."], type: "static" },
  { pattern: /きょへさんは喋らないんですか|きょへさん喋らないんですか|きょへさんは喋らないの？|きょへさん喋らないの？/, responses: ["文字なんて打ってないでまずはあなたがミュート解除してみませんか？^^ﾆｯｺﾘ"], type: "static" },
  { pattern: /きょへにいこんにちは/, responses: ["くらげちゃんこんにちは！"], type: "static" },
  { pattern: /きょへにいこんばんは/, responses: ["くらげちゃんこんばんは！"], type: "static" },
  { pattern: /きょへにいやぁやぁ|きょへにいやあやあ/, responses: ["やあやあ！ｗ"], type: "static" },
  { pattern: /きょへ。?さんの体操/, responses: ["昔の跳馬の映像あったよ", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/160824_155613.mov?v=1702759298994"], type: "static" },
  { pattern: /きょへ。?さんハートください|きょへ。?さんハート下さい/, responses: [`いいよ。後で送っておくね。<@530155393117192203>`], type: "static" },
  { pattern: /きょへ。?の身長|きょへ。?さんの身長/, responses: ["180㎝までもう少し！！","-# 普通に175cmですぅ～…"], type: "static" },
  { pattern: /きょへ。?の体重|きょへ。?さんの体重/, responses: ["大学の頃からずっと64kg"], type: "static" },
  { pattern: /きょへ。?の住所|きょへ。?さんの住所/, responses: ["ピカチュウ王国"], type: "static" },
  { pattern: /きょへ。?は無職|きょへ。?さんは無職/, responses: ["無職じゃねえ！！！！！！！！（無職）"], type: "static" },
  { pattern: /きょへ。?はニート|きょへ。?さんはニート/, responses: ["ニートじゃねえ！！！！！！！！","-# 引 き こ も り ！","DA☆！"], type: "static" },
  { pattern: /きょへ。?の職業|きょへ。?さんの職業/, responses: ["肩書き：夢追い人（※現実逃避中）"], type: "static" },
  { pattern: /きょへ。?の趣味|きょへ。?さんの趣味/, responses: ["趣味…なんだろ…。アニメ見たりYouTube見たり、skyしたり、ふらっと動画作ったり、キャンマラしたり、検証したり、BOT作ったり、料理作ったり、PC系の情報調べたり、ChatGPTと話したり、人生観の話したり…。\nと、少ないよ！"], type: "static" },
  { pattern: /きょへ。?の性格/, responses: ["どんな性格だと思う？"], type: "static" },
  { pattern: /あっときょへ/, responses: ["せめてメンションしろスニャ", `はぁ…。さっさと来い<@530155393117192203>`], type: "static" },

  //羽系
  { pattern: /孤島の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "９枚\n→(メインエリア➄＋試練➃)", type: "static" },
  { pattern: /草原の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "２4枚\n→(蝶々の住処➂＋洞窟➁＋鳥の巣➁＋浮島➃＋神殿上部➁＋楽園➇＋草原連邦➂)", type: "static" },
  { pattern: /雨林の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "１９枚\n→(最初のエリア➁＋小川➃＋ツリーハウス➁＋神殿前➂＋神殿奥➀＋晴れ間エリア➁＋晴れ間地下エリア➃＋風の街道➀)", type: "static" },
  { pattern: /峡谷の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "１７枚\n→(スライダー左列➀＋スケートリンク➁＋天球儀➁＋空レース➁＋陸レース➀＋レース後半➀＋神殿前➀＋神殿内➀＋夢見➂＋劇場➀＋隠者➁)", type: "static" },
  { pattern: /捨て地の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "１８枚\n→(秘宝の座礁➁＋最初のエリア➁＋エビ１匹エリア➁＋エビ４匹エリア➃＋座礁船➂＋神殿前➁＋神殿内➀＋忘れられた方舟➁)", type: "static" },
  { pattern: /書庫の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "１６枚\n→(地下➁＋１階➀＋３階➀＋４階➁＋５階➀＋最上階➀＋保存庫➀＋星月夜の砂漠➂＋三日月オアシス➂＋ムーミン谷➀)", type: "static" },
  { pattern: /(暴風域|原罪|現在)の?(羽|翼|光の翼|光の子|枚数)/i,
    responses: "１０枚\n→(第一エリア➀＋第二エリア➈)", type: "static" },
  { pattern: /光の翼の総数は|羽の総数は|光の羽の総数は|全エリアの羽|全エリアの羽|全エリアの翼|全エリアの光の翼|全エリアの光の子|全ての枚数|全ての翼|全ての光の翼|全ての光の子|全ての枚数|全翼|全光の翼|全光の子|全枚数|光の子の合計は/,
    responses: "合計119枚（113枚+追想6枚）\n→(孤島9 + 草原24 + 雨林19 + 峡谷17 + 捨て地18 + 書庫16 + 暴風域10 + 追想6)", type: "static" },

  //火種系 static
  { pattern: /(火種|光の(かけら|カケラ|欠片))の(スプレッド|量|一覧|表)/i,
    responses: ["https://docs.google.com/spreadsheets/d/1Y5nDH81N3rpbvWhwSY_DgvTCA2mXAKeF2-RmorIN2WE/edit#gid=1739335542"], type: "static" },
  { pattern: /ホームの?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["23個"], type: "static" },
  { pattern: /花鳥卿の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["23個 + シナモンロール50 + アリスカフェ284"], type: "static" },
  { pattern: /孤島の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["885個"], type: "static" },
  { pattern: /試練の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["水106 + 地115 + 風200 + 火200"], type: "static" },
  { pattern: /草原の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["691 + 151(亀の背中の闇花51 + ←を焼いた後に出る地上の貝100) + 水中の貝α(200前後)"], type: "static" },
  { pattern: /貝の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["【楽園夕日時の貝】\n　  大：30\n小(開)：30\n小(閉)：10～20"], type: "static" },
  { pattern: /雨林の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["893(日,月,水,金)/894(火,木,土)個"], type: "static" },
  { pattern: /峡谷の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["882 + 劇場の花α + 隠者レース150+α"], type: "static" },
  { pattern: /捨て地の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["545(月,水,金)/546(火,木,土)/660個(日)　+ 貝ｘ"], type: "static" },
  { pattern: /書庫の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["801個"], type: "static" },
  { pattern: /原罪の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["一個もないよ！(天空にはあるよ)"], type: "static" },
  { pattern: /天空の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["最大で225　（精霊/フレに触れると5。精霊最大30体、フレ最大15人"], type: "static" },
  { pattern: /(劇場|音楽堂|楽譜|楽譜チャレンジ|演奏)の?(光のカケラ|光のかけら|火種|ワックス|演奏|楽譜|音楽|)/i,
    responses: ["上手く出来れば100個(結果次第では50)"], type: "static" },
  { pattern: /ウニ焼きの?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["250～350/10分　上限1011個"], type: "static" },
  { pattern: /ウナギの?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["500/約12.5分 上限500個"], type: "static" },
  { pattern: /(パン|ぱん)の?(光のカケラ|光のかけら|火種|ワックス)/i,
    responses: ["約600個/10分 上限1000個"], type: "static" },
  { pattern: /今月のイベント/i,
    type: "delegate",
    id: "postMonthlyEventsHandler" },
  { pattern: /(現在|進行中|今)のイベント/i,
    type: "delegate", 
    id: "remindCurrentEventsHandler" },

  //古いネタ・ネットネタ系 static
  { pattern: /今北産業/,
    responses: ["遅かったね～やっと来たか～。…1行以上喋る事ないよ。"], type: "static" },
  { pattern: /kwsk/, 
    responses: ["俺も聞きたい。頼む"], type: "static" },
  { pattern: /wktk/, 
    responses: ["+　　　+\n      ∧＿∧ +　　+\n（0゜･∀･）  ﾜｸﾜｸ　+\n（0ﾟ つと)　+ ﾃｶﾃｶ\nと＿_）＿）　 +　+"], type: "static" },
  { pattern: /ガクブル|gkbr/, 
    responses: ["((( ；ﾟДﾟ)))"], type: "static" },
  { pattern: /もちつけ/,  
   responses: ["うっす。\nhttps://cdn.discordapp.com/attachments/1022093564995436594/1217024733170761728/GreenKirby.gif"], type: "static" },
  { pattern: /リア充/,  
   responses: ["爆はt.........応援してます♡"], type: "static" },
  { pattern: /くぁwせdrftgyふじこlp/, 
    responses: ["令和世代に通じないってそれｗ"], type: "static" },
  { pattern: /ggrks/, 
   responses: ["弊社はggrksサービスを応援しております。\nhttps://www.google.com/?gws_rd=ssl"], type: "static" },
  { pattern: /飯テロ/, 
    responses: ["便乗します\nhttps://cdn.discordapp.com/attachments/1022093564995436594/1217024722395594822/Binzyou.jpg"], type: "static" },
  { pattern: /お邪魔します|おじゃまします/, 
    responses: ["邪魔するなら帰って～"], type: "static" },
  { pattern: /はいよー/,  
    responses: ["からの～？"], type: "static" },
  { pattern: /知らんけど/, 
    responses: ["知らんよな。知らんけど。"], type: "static" },
  { pattern: /時すでにお寿司/, 
    responses: ["ネタの賞味期限切れなのよｗ　…寿司だけにね!!!!"], type: "static" },
  { pattern: /かにかに/,
    responses: ["タラバガニ～かにかにズワイガニ～"], type: "static" },
  { pattern: /ヨシ！|現場猫|アイルー/, 
    responses: ["https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/genba-neko-yoshi.mov?v=1702753147187"], type: "static" },
  { pattern: /ハッピー|Happy/, 
    responses: ["https://tenor.com/view/happy-happy-happy-happy-happy-cat-happy-dancing-cat-gif-716006509349864265"], type: "static" },

  //特定の地雷 static
  { pattern: /ｳｵｵｵｵｱｱｱｱ|ｱﾞｱﾞｱﾞｱﾞ/, 
    responses: ["うるさいぞズマ"], type: "static" },
  { pattern: /興奮した？/, 
    responses: ["すみません、興奮して止まらなくなっちゃいました"], type: "static" },
  { pattern: /知らんがな|知らんて|知らないよ|知らないって/,
    responses: ["いやそれくらい簡単だろ…知っておけよ…。"], type: "static" },
  { pattern: /ｴﾍﾍ/, 
    responses: ["(´>∀<｀)ゝ))ｴﾍﾍ"], type: "static" },
  { pattern: /誰がハゲだ|誰がハゲじゃ/, 
    responses: ["鏡見てから出直してこいｗ"], type: "static" },
  { pattern: /カービィ?/, 
    responses: ["https://cdn.discordapp.com/attachments/932595932464291872/1088570386255454368/kabiiiiiiiii.gif"], type: "static" },
  { pattern: /おい！/, 
    responses: ["なに！！"], type: "static" },
  { pattern: /カードちょうだい|カードくれ/, 
    responses: ["まずは30万振り込んでね"], type: "static" },
  { pattern: /カード出せ|カードだせ/, 
    responses: ["お金を入れてからにして！"], type: "static" },
  { pattern: /カード出るの？|カードでるの？/, 
    responses: ["あ…怪しくないよ…！信じてよ…！"], type: "static" },
  { pattern: /もう一回|もう1回|もう１回/, 
    responses: ["じゃあ、またお金を入れてね！カードが貰えるよ！"], type: "static" },
  { pattern: /無料でお願い/, 
    responses: ["おいおい…！\n# 慈善事業じゃねえ！"], type: "static" },
  { pattern: /お金入れたのに|振り込んだのに/, 
    responses: ["いや～なんでっスかね～。こっちも確認出来てないんㇲよね～"], type: "static" },
  { pattern: /詐欺じゃん/, 
    responses: ["誹謗中傷はやめてください！"], type: "static" },
  { pattern: /うるさい/, 
    responses: ["そーだそーだ！うるさいぞー！だまれだまれー！やーいやーーーい！！"], type: "static" },
  { pattern: /BOTなのに生意気|生意気なBOT/i, 
    responses: ["誰に文句言ってるんだ人間のくせに"], type: "static" },
  { pattern: /だるい/, 
    responses: ["そんなあなたに！Ctrl+Alt+Del"], type: "static" },
  { pattern: /友達いない/, 
    responses: ["ﾄﾓﾀﾞﾁ…ﾅﾆｿﾚ…ｵﾃﾞ…ﾄﾓﾀﾞﾁ…欲しい！👁👁"], type: "static" },
  { pattern: /通知きた/, 
    responses: ["そう！優秀でしょ！"], type: "static" },
  { pattern: /風呂入る|風呂行ってくる|風呂いてき|風呂いってき|風呂はいってく/, 
    responses: ["いってら～！てかお風呂と言えばたっつんの風呂長過ぎよな？"], type: "static" },
  { pattern: /Amazon/, 
    responses: ["https://www.google.com/aclk?sa=L&pf=1&ai=DChsSEwizq5i5zPqTAxV30RYFHfPrE_kYACICCAEQABoCdGw&co=1&ase=2&gclid=Cj0KCQjw-pHPBhCdARIsAHXYWP8ip8mN146Dvfdhk7SksUHQil_-L7hfj9KhZKjnPm_UZ7HGAKhSAeIaAk3TEALw_wcB&cid=CAAS0gHkaPDvt7sndSvCI-L44yExlJlx_zBJE8cvay0VNGf4bPMko5yy5ZrSQMef8PS-3IW6nXJ8BJhSsCvLZsggNwkvrc-8qoAXKCju5AJ9OcrudozfHulxEFzgCov9frgRqnBoXdSCax4iENbOmGE4XH5ZbonBryUPMAmnBBD2n4TGRIqLwIGO7Ig0Ga1VvkV_vZm8fxe8FDIeri-hGO-2kptKDaqAW-hCgEnHjtR-v59dFnKOGSoMvJduVw0fnyEOO0gsyyCwXM6LzCyUcvw00WEM5tU&cce=2&category=acrcp_v1_32&sig=AOD64_2_8qXITVblQ_-qc0e7VoEWPsD4Xg&q&nis=4&adurl=https://www.amazon.co.jp/?%26tag%3Dhydraamazonav-22%26ref%3Dpd_sl_7ibq2d37on_e%26adgrpid%3D157529192841%26hvpone%3D%26hvptwo%3D%26hvadid%3D675114138690%26hvpos%3D%26hvnetw%3Dg%26hvrand%3D8771536878770092403%26hvqmt%3De%26hvdev%3Dc%26hvdvcmdl%3D%26hvlocint%3D%26hvlocphy%3D9189909%26hvtargid%3Dkwd-10573980%26hydadcr%3D27922_14701883&ved=2ahUKEwjWo4u5zPqTAxUgklYBHWWdG1kQ0Qx6BAgMEAE"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /ぱたああああああーーーん/, 
    responses: ["れすぽんすぅ～～～～～～～"], type: "static" },
  { pattern: /お金入れました|振り込んだ|振り込みした/, 
    responses: ["証拠はどこよ証拠は！見せなさい！"], type: "static" },
  { pattern: /分割でも?いい？|分割払いで/, 
    responses: ["分割かあ…まあ120回くらいにしておく？"], type: "static" },
  { pattern: /PayPay送った|PayPayで送った|PayPayでいい？/, 
    responses: ["誠に申し訳ございません。当店のサービスは銀行振込のみとなっております。なので早く払え"], type: "static" },
  { pattern: /振り込んだ|お金いれた/, 
    responses: ["証拠はどこよ証拠は！見せなさい！"], type: "static" },
  { pattern: /証拠だ|これが証拠|はい証拠|証拠どうぞ/,
    responses: ["おいおい！PDFでメール送付だろ！"], type: "static" },
  { pattern: /shovel blueは|shovelblueは/, 
    responses: ["頻繁に重たくなるからスニャイヴォットを使おう！"], type: "static" },
  { pattern: /shovel redは|shovelredは/, 
    responses: ["赤い。"], type: "static" },
  { pattern: /shovel greenは|shovelgreenは/, 
    responses: ["そもそも呼びかけに反応しない時があるｗ"], type: "static" },
  { pattern: /hey k-bot|ヘイk-bot|へいk-bot|heyケーボット|ヘイケーボット|へいケーボット|heyけーぼっと|ヘイけーぼっと|へいけーぼっと/, 
    responses: ["すみません。よくSiriません。"], type: "static" },
  { pattern: /OK k-bot|オッケーk-bot|おっけーk-bot|おっけーケーボット|オッケーケーボット|オッケーボット|おっけーけーぼっと|オッケーけーぼっと|おっけーぼっと/, 
    responses: ["すみません、よくわかり…\n# 黙れ小僧！"], type: "static" },
  { pattern: /働けー?bot|働k-bot|働けーぼっと|働けーボット|働ケーボット/, 
    responses: ["すみません、ちょっとだけーボーットしてました。"], type: "static" },
  { pattern: /捨て地の?キャンマラ/, 
    responses: ["捨て地で…キャンマラ…？？？そんなものは無いよ…。"], type: "static" },
  { pattern: /充電が３％|充電が3％|充電が３%|充電が3%|充電３％|充電3％|充電３%|充電3%/, 
    responses: ["まだまだ充電せんでも余裕だね。焦らなくていいよ。"], type: "static" },
  { pattern: /充電が２％|充電が2％|充電が２%|充電が2%|充電２％|充電2％|充電２%|充電2%/, 
    responses: ["まだ充電せんでも大丈夫よ。焦らず焦らず。。"], type: "static" },
  { pattern: /充電が１％|充電が1％|充電が1%|充電１％|充電1％|充電1%/, 
    responses: ["今すぐ充電しろ or 諦めろ"], type: "static" },
  { pattern: /( *ˊᵕˋ)ɢᵒᵒᵈ ɴⁱᵍᑋᐪ/, 
    responses: ["しぃちゃんさんおやすみ～"], type: "static" },
  { pattern: /ｹﾗｹﾗ/, 
    responses: ["(´∀｀*)ｹﾗｹﾗ"], type: "static" },
   { pattern: /ｿｫｰｯ/,
    responses: "知る人ぞ知るk-botの黒歴史の文字列『ｿｫｰｯ』" , type: "static"},
  { pattern: /HA☆HA☆HA☆/,
    responses: "ばんちょさん笑ってるｗ" , type: "static"},
  { pattern: /おやうみなさい/,
    responses: "おやうみじゃねーよ" , type: "static"},
  { pattern: /おやうみやさい/,
    responses: "うるさいぞ。ティッシュ。" , type: "static"},
  { pattern: /スプラやりたい/,
    responses: "思い立ったが吉日よ　\nhttps://store-jp.nintendo.com/list/software/70010000046394.html" , type: "static"},
  { pattern: /完璧です/,
    responses: "ありがとうございます！何が？" , type: "static"},
  { pattern: /たっつんの頭/,
    responses: "割ったら中から黄身が出てきますから気を付けてくださいね…。" , type: "static"},
  { pattern: /まるみや|マルミヤ|丸美屋/,
    responses: ["チャッチャッチャ　丸美屋　の　まぜこみわかめ～♪",
               "https://www.marumiya.co.jp/"] , type: "static"},
  { pattern: /麻婆豆腐|マーボー豆腐/,
    responses: "https://i.ytimg.com/vi/Myqnk5iOb30/mqdefault.jpg" , type: "static"},
  { pattern: /沖縄は/,
    responses: "沖縄といえば…なにが有名？" , type: "static"},
  { pattern: /サーターアンダギー/,
    responses: "あー知ってる知ってる、おにぎりみたいなやつでしょ？" , type: "static"},
  { pattern: /シーサー/,
    responses: "確かに、シーサーとは沖縄のハチ公！ってよく聞くよねえ～" , type: "static"},
  { pattern: /沖縄そば/,
    responses: "地名+そばって言えば原産ぽっくなるのずるくない？ 北海道牛乳も名産にしていい？" , type: "static"},
  { pattern: /ちんすこう/,
    responses: "結局ちんすこうって何？魚の名前？" , type: "static"},
  { pattern: /琉球王国/,
    responses: "ズマ氏の出身国じゃないですかwww" , type: "static"},
  { pattern: /たっつんハゲ|たっつんはげ/,
    responses: "https://discord.com/channels/930348999196676167/932595932464291872/1064546142941102133" , type: "static"},
  { pattern: /なるほど～/,
    responses: "あ～この言い方はスニャちゃかてんちゃんさんだけど、統計学的にきっとスニャちゃかな？" , type: "static"},
  { pattern: /ピカチュウ使いは/,
    responses: "惹かれ合う。ドドン。" , type: "static"},
  { pattern: /最近の若いのは/,
    responses: "あんたも若いだろ" , type: "static"},
  { pattern: /タマゴは|たまごは|🥚は/,
    responses: "たっつん" , type: "static"},
  { pattern: /ロリコンです/,
    responses: "いいえ、あなたはロリコンコンコンです。" , type: "static"},
  { pattern: /スカイ窓主|Sky窓主|sky窓主/,
    responses: "いやピカチュウ窓主ですけど…。" , type: "static"},
  { pattern: /おはようございます☀/,
    responses: "seiさんおはようございます☀" , type: "static"},
  { pattern: /死んだ|死にました/,
    responses: "https://tenor.com/view/dancing-coffin-dancing-pallbearers-funeral-dance-gif-16837090" , type: "static"},
  { pattern: /なるほも/,
    responses: "seiさんはホモ？OKOK" , type: "static"},
  { pattern: /あたりまえ体操/,
    responses: "ネタ古くない？ｗ" , type: "static"},
  { pattern: /寝たくない/,
    responses: "駄々こねずに寝ろ！！" , type: "static"},
  { pattern: /シーチキン|チキン|日食|月食/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ｼﾁｷﾝ.png?v=1742197608683" , type: "static"},
  { pattern: /カツオ/,
    responses: "https://i.pinimg.com/236x/29/07/30/290730c4f2a2a2b59bea0118b63c7a7c.jpg" , type: "static"},
  { pattern: /五時った/,
    responses: "水ッた" , type: "static"},
  { pattern: /こじんまり/,
    responses: "こじんまりって書きがちだけど本当は『こぢんまり』なんだってね" , type: "static"},
  { pattern: /呪術海鮮/,
    responses: "うゆ。" , type: "static"},
  { pattern: /きょれさん|おもしろかつまた|面白かつまた|おもしろかつた|面白かつた|たのしかつた|楽しかつた|たのしかつまた|楽しかつまた/,
    responses: "ｗｗｗお前ｗｗｗ 五時ってやんのｗｗｗ" , type: "static"},
  { pattern: /かっこいいすごいきゃ/,
    responses: "へこうるさい" , type: "static"},
  { pattern: /オ?ススメの食べ物は|オ?ススメのたべものは|おすすめのたべものは|おすすめの食べ物は/,
    responses: ["☆ 海・鮮・丼 ☆",
               "https://omocoro.jp/assets/uploads/2019/04/1554466114d9ein.jpg"], type: "static"},
  { pattern: /自律感覚絶頂反応/,
    responses: ["呼びました？？",
               "https://youtu.be/dIytbctX0iE"], type: "static"},
  { pattern: /ESAMは|Esamは|esamは/,
    responses: "神の🥚" , type: "static"},
  { pattern: /サーモンのねぎ塩ユッケ|サーモンのネギ塩ユッケ/,
    responses: ["マジでおいしそうだよな",
               "https://pbs.twimg.com/media/FdUV0C0VEAI4AXR?format=jpg&name=large"], type: "static"},
  { pattern: /回文/,
    responses: "きいろいしんぶんし" , type: "static"},
  { pattern: /deepl|Deepl|deepL|DeepL|DEEPL/,
    responses: "https://www.deepl.com/ja/translator" , type: "static"},
  { pattern: /誕生日おめでと/,
    responses: ["おめでとーーー！！！🎊✨㊗",
               "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/medium.gif?v=1677097580867"], type: "static"},
  { pattern: /いい加減にせい|いいかげんにせい/,
    responses: "https://cdn.discordapp.com/attachments/1007569901457780827/1066750192747028530/e0cb6e42fac93ce7.mp4" , type: "static"},
  { pattern: /絶体正解|絶体間違えない|クイズ/,
    responses: "絶体正解するクイズ「食文化を支えているのは農家である。Yesか農家で答えて下さい。」" , type: "static"},
  { pattern: /寝るのだ/,
    responses: "https://i.pinimg.com/originals/6c/83/b2/6c83b24dc9279cd33e59957af32569a1.jpg" , type: "static"},
  { pattern: /手を上げ|手をあげ|挙手/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ｿﾞｳ.png?v=1742199485077" , type: "static"},
  { pattern: /どうぞ！|道を譲|先に?行って|先に?いって|先に?やって|先に?遊んで|先に?始めて/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ﾄﾞｳｿﾞ.png?v=1742199583148" , type: "static"},
  { pattern: /立たないと|水位が|死ぬよ|しぬよ|ハイジ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/水死.png?v=1742199610963" , type: "static"},
  { pattern: /あばよ|アバヨ|注射/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ｱﾊﾞﾖ?v=1742199616025" , type: "static"},
  { pattern: /石鹸|せっけん|助けていただいた|助けてもらった/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/石鹸?v=1742199625595", type: "static" },
  { pattern: /クワガタ|くわがた|ｸﾜｶﾞﾀ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ｸﾜｶﾞﾀ?v=1742199632668", type: "static" },
  { pattern: /どこでもドア|どあほ|ドアホ|ドあほ|どアホ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ﾄﾞｺﾃﾞﾓﾄﾞｱﾎ?v=1742199636340", type: "static" },
  { pattern: /あーん|アーン/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ｱﾝ?v=1742199644627", type: "static" },
  { pattern: /汁物|知るもの|しるもの|ご飯食?べたい|ごはん食?べたい/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/たまご?v=1742199651284", type: "static" },
  { pattern: /藤井壮太|藤井聡太/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/藤井?v=1742199656690", type: "static" },
  { pattern: /ﾚｼﾞﾌﾞｸﾛ|レジ袋|レジぶくろ|4ゴールド|４ゴールド|4G|４G|4Ｇ|４Ｇ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ﾚｼﾞﾌﾞｸﾛ?v=1742199662929", type: "static" },
  { pattern: /子豚|狼|こぶた|コブタ|子ぶた|子ブタ|おおかみ|オオカミ|ｵｵｶﾐ|レンガ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/3匹の子豚?v=1742199668876", type: "static" },
  { pattern: /指痛|指挟|指紫|ドアで?挟|ドアに?挟/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ﾕﾋﾞｲﾀｲ?v=1742199691819", type: "static" },
  { pattern: /リコーダー/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ﾅﾒﾅﾒ?v=1742199695454", type: "static" },
  { pattern: /ほんとにも|ホントにも|本当にも|ほんとにさ|ホントにさ|本当にさ/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/ほんとにもう?v=1742199698578", type: "static" },
  { pattern: /ボケてえええええ11112222/,
    responses: "URL", type: "static" },
  { pattern: /Www/,
    responses: "WwWwWwWwWwWwWwWw　This is grass", type: "static" },
  { pattern: /最古のツイート/,
    responses: "https://twitter.com/gmexNK/status/408449010718879744?t=dQPiCpMRMFVLR8AYhOTiNQ&s=19", type: "static" },
  { pattern: /想像の斜め上/,
    responses: "『想像の斜め上』…とは、興味深い表現をするね。ただ、それだと曖昧だからその程度や範囲はどのようなものなのか、少し詳しく教えてほしいなあ？想像の座標に対してどの方向に対して斜め上を言っているんでしょうか。そもそも向いている座標によって斜めって変わりますし、そもそも斜めの定義って人それぞれだと思いますが基準に対して何度ズレたら斜めと呼びますか？いやそもそも想像って正面とか基準とかそんな概念があるんですかね？そこのところ今一度擦り合わせをしたうえで……", type: "static" },
  { pattern: /シュミレーション/,
    responses: "シュミレーションじゃなくてシミュレーションだよ", type: "static" },
  { pattern: /コミニュケーション/,
    responses: "コミニュケーションじゃなくてコミュニケーションだよ！コミュニはコミュニだからコミュニはコミニュじゃないよ！コミュニがコミニュと間違えないようにコミュニコミニュコミュニコミニュと復唱して覚えよう！！", type: "static" },
  { pattern: /くそかわいい|クソかわいい|くそ可愛い|クソ可愛い/,
    responses: "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/389ab7d086cefbef.mp4?v=1702825472889", type: "static" },
  
//おススメの〇〇系 static
  { pattern: /オ?ススメのキャンマラルート|オ?ススメのキャンマラ/i,
  responses: ["このルートがオススメ！\nhttps://youtu.be/FA6heQJNHEU?si=5-Ndg5qkGZKvCUIW"], type: "static" },
{ pattern: /お?ススメのYouTuber?|オ?ススメのチャンネル|オ?ススメの動画|おすすめの動画|おすすめのYouTuber?|おすすめのチャンネル/i,
  responses: ["天才のチャンネルを紹介\nhttps://www.youtube.com/channel/UCf3RsOFeg5MdGv_UJLZE5iw"], type: "static" },
{ pattern: /オ?ススメのbot|お?ススメのBot|オ?ススメのボット|お?ススメのボット/i,
  responses: ["そりゃあ…天才が生み出した天才のBot...。その名もK-bot!!!"], type: "static" },
{ pattern: /オ?ススメのホラゲー|お?すすめのホラゲー/i,
  responses: ["これなんかおススメよ！\nhttps://kusoi.site/2020/06/18/pien-g01/"], type: "static" },
{ pattern: /オ?ススメの服窓主|お?すすめの服窓主|オ?ススメの副窓主|お?すすめの副窓主/i,
  responses: ["https://x.com/Pikashou0414"], type: "static" },
{ pattern: /オ?ススメの窓主|オ?ススメのまどぬし|お?すすめの窓主|お?すすめのまどぬし/i,
  responses: ["聞くまでも無いやろがい！！！", "おれ。\nhttps://www.youtube.com/channel/UCIcsBVzRT-Hvz6bdM13rvfQ"], type: "static" },
{ pattern: /お?ススメの?羽マラ|お?ススメの?羽集め|羽マラの?やり方|羽マラの?解説|羽マラの?動画|羽マラの?ルート|羽マラの?ショトカ/i,
  responses: ["世界的な天才が羽マラの動画アップしてたよ\nhttps://youtu.be/iD1P9bAW8WY"], type: "static" },
{ pattern: /オ?ススメのお菓子|オ?ススメのおかし|おすすめのお菓子|おすすめのおかし/i,
  responses: ["カルビー 堅あげポテト BIG うすしお味 150g×12袋　Amazonリンクも貼っとくよ♡ \nhttps://x.gd/zmiKo"], type: "static" },
{ pattern: /オ?ススメの曲は|おすすめの曲は/i,
  responses: ["共感できる系の曲ならコレ\nhttps://youtu.be/BhQDqdCHZOI"], type: "static" },
{ pattern: /オ?ススメの飲み物|おすすめの飲み物|オ?ススメのジュース|おすすめのジュース/i,
  responses: ["コーラ一択！と言いたいけど、たまにのむ三ツ矢サイダーも最高なんだよねええええ～！！！"], type: "static" },
{ pattern: /オ?ススメの紙コップ|おすすめの紙コップ/i,
  responses: ["そんな事聞く人あなたくらいですよ？", "https://askul.c.yimg.jp/img/product/3L1/2308828_3L1.jpg"], type: "static" },
{ pattern: /オ?ススメのショトカ|おすすめのショトカ/i,
  responses: ["個人的には試練のおんロケショトカが期待値高くてオススメ。あとは、無難に書庫のおんロケショトカ"], type: "static" },
{ pattern: /オ?ススメのケープ|おすすめのケープ/i,
  responses: ["あなたなら\n　どんなケープも\n　　似合うわよ\n季語無し"], type: "static" },
{ pattern: /オ?ススメの食べ物|オ?ススメのたべもの|おすすめのたべもの|おすすめの食べ物/i,
  responses: ["☆ 海・鮮・丼 ☆", "https://omocoro.jp/assets/uploads/2019/04/1554466114d9ein.jpg"], type: "static" },
{ pattern: /オ?ススメのパソコン|おすすめのパソコン|オ?ススメのPC|おすすめのPC/i,
  responses: ["M2 or M3 チップ搭載してるMacBookPro、メモリは8GB以上。ただしゲームしたいならWindowsの方が良いかも。WindowsならCPUがi7、メモリは8GB以上。でもあなたのやりたい事次第。"], type: "static" },

//sky系 static
  { pattern: /今日の?デイリー|今日の?シーズンキャンドル|今日の?大キャン/,
    responses: ["黒沢さんのツイートはこちら\n👇　　　👇　　　👇\nhttps://x.com/sky_box0324?s=20\n",
               "9bitの情報はこちら\n👇　　　👇　　　👇\nhttps://9-bit.jp/skygold/6593"], type: "static" },    
  { pattern: /原罪マップ/,
    responses: ["これを見な",
               "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/kyoheVer.jpg?v=1683557962502"], type: "static" },    
  { pattern: /９BIT|９bit|9bit|9BIT|9Bit|9-bit/,
    responses: "https://9-bit.jp/skygold",
    type: "static" }, 
  { pattern: /てすてすてすと/,
    responses: "https://cdn.discordapp.com/attachments/954865403006451752/1216850076878766283/SKY_20240309_234527_.jpg",
    type: "static" },
  { pattern: /skyは|Skyは/,
    responses: "skyについてだね！HPのリンクを貼っておくから見てみるといいよ!!\nhttps://www.skygroup.jp/",
    type: "static" },
  { pattern: /風の試練の?ショトカ|風の試練の?裏入り?口|風の試練の?裏入場/,
    responses: "👇過去の栄光はコチラ👇\nhttps://youtu.be/XTi26--jdgc?si=ZFMNwtO3Co-QG6EI",
    type: "static" },
  { pattern: /水の試練の?ショトカ|水の試練の?裏入り?口|水の試練の?裏入場/,
    responses: "👇過去の栄光はコチラ👇\nhttps://youtu.be/IUUbNGUlI3A",
    type: "static" },
  { pattern: /地の試練の?ショトカ|地の試練の?裏入り?口|地の試練の?裏入場/,
    responses: "👇過去の栄光はコチラ👇\nhttps://youtu.be/sSxkP6s-zAU",
    type: "static" },
  { pattern: /火の試練のショトカ1|火の試練のショトカ１/,
    responses: "https://youtu.be/v3pO7sbAvXM?si=ym9Az4Jtz8kVkhS9",
    type: "static" },
  { pattern: /火の試練のショトカ2|火の試練のショトカ２/,
    responses: "https://youtu.be/4JynriDGxYc?si=hhFeWS5VK3i6TPQq",
    type: "static" },
  { pattern: /火の試練のショトカ3|火の試練のショトカ３/,
    responses: "https://youtu.be/4JynriDGxYc?si=hhFeWS5VK3i6TPQq",
    type: "static" },
  { pattern: /火の試練のショトカ4|火の試練のショトカ４|火の試練の裏入り口|火の試練の裏入場/,
    responses: "https://youtu.be/4JynriDGxYc?si=hhFeWS5VK3i6TPQq",
    type: "static" },
  { pattern: /火の試練のショトカ5|火の試練のショトカ５/,
    responses: "https://youtu.be/pXKG1NfmHL4?si=Z7uAfEbRfT40aFko",
    type: "static" },
  { pattern: /火の試練の?ショトカ/,
    responses: "火の試練のショトカ1～5のどれがいい？\n\n1. 王道ルート\n2. おんロケルート\n3. 一本道ルート\n4. 裏入り口ルート（修正済）\n5. ソロ安定ルート\n\n火の試練のショトカ（数字）　の形式で入力してね\n例→「火の試練のショトカ1」",
    type: "static" },
  { pattern: /トビウオの?解説|トビウオの?動画|トビウオの?やり方|とびうおの?解説|とびうおの?動画|とびうおの??やり方/,
    responses: "https://youtu.be/E9eEicAsZh4?si=jOqMpQn2khK7my93",
    type: "static" },
  { pattern: /めんどくさい時の?キャンマラ|めんどい時の?キャンマラ|めんどい時用キャンマラ|めんどくさい時用の?キャンマラ/,
    responses: "https://youtu.be/VDJFrFNd-BE?si=_7u0O50uUG8qZHTJ\nhttps://docs.google.com/spreadsheets/d/12lRf_nvsWpwEEGgJAMew3pd16w8yf-Fco7WuSrbGa2s/edit?usp=sharing",
    type: "static" },
  { pattern: /キャンマラめんどくさい|キャンマラめんどい|18本キャンマラ/,
    responses: "そんなあなたにはこのキャンマラがオススメ！ \nhttps://youtu.be/VDJFrFNd-BE?si=_7u0O50uUG8qZHTJ",
    type: "static" },
  { pattern: /変態キャンマラ|へんたいキャンマラ/,
    responses: "ふ～っふっふ…！！\nhttps://youtu.be/746mahW8Ivs?si=vsGE5WrvyRLIwqlB",
    type: "static" },
  { pattern: /ソロ19本キャンマラ|19本キャンマラ/,
    responses: "ソロ用19本キャンマラルートはこちら！　\n(サブありが見たければ「サブあり19本」って入れてね！)　\nhttps://youtu.be/FA6heQJNHEU?si=R-bdyLMLPH7CH6g_",
    type: "static" },
  { pattern: /サブあり19本キャンマラ|サブありキャンマラ|サブキャンマラ|サブ19本キャンマラ|サブあり19本/,
    responses: "https://youtu.be/FulRMyT8ubw?si=BBmDAfc0hyfQYFjn",
    type: "static" },
{ pattern: /灰キャンRTA|灰キャン世界最速|最速灰キャン|灰キャン最速/, 
  responses: "ふ～っふっふ…！！　\nhttps://youtu.be/Ba4QDCN0S-4?si=IkF47khEy-I2skA4", type: "static" },
{ pattern: /効率よくキャンマラする方法|効率良くキャンマラする方法|効率の?いいキャンマラ|効率の?良いキャンマラ/, 
  responses: "https://youtu.be/nUo5MxjTq1Q?si=NktbPxbMQYgmgIh7", type: "static" },
{ pattern: /原罪のルート|原罪のショトカ|原罪の動画/, 
  responses: "https://youtu.be/Ew921TnFoaw?si=Ic79rsavyEZPTokJ", type: "static" },
{ pattern: /ペンギンの?取?り方|ペンギンの?とり方|ペンギンの?取?かた|ペンギンの?解説|ペンギンの?動画/, 
  responses: "これで取れるよ\nhttps://youtu.be/cxksGI_H3SI", type: "static" },
{ pattern: /映画暗黒龍|暗黒龍の?映画|暗黒龍の?動画/, 
  responses: "ふっふっふ……。\nhttps://youtu.be/r9S3GdQQlxE", type: "static" },
{ pattern: /映画雀|雀の?映画|雀の?動画|映画すずめ|すずめの?映画|すずめの?動画|映画スズメ|スズメの?映画|スズメの?動画/, 
  responses: "ふっふっふ……。\nhttps://youtu.be/fZamVz7LZU0", type: "static" },
{ pattern: /闇のかけらの?場所|闇のカケラの?場所|闇の欠片の?場所|シャードの?場所|シャードどこ？|シャードどの?エリア|今日の?シャード|今日の?闇の/, 
  responses: "今日のシャードはここ！　\nhttps://9-bit.jp/skygold/23767/", type: "static" },
{ pattern: /垂直飛?びの?やり方|垂直飛?びの?解説|垂直飛?びの?動画/, 
  responses:["👇　コントローラー勢はこちら　👇\nhttps://youtu.be/YrT7Dy3OGMo?si=fZ5dI1GLX4cReTia", ".\n\n👇　スマホ勢はこちら　👇　\nhttps://youtu.be/vy4rG2rZKcM?si=1OvSyO4wD78HPeDB"], type: "static" },
{ pattern: /デイリーライトの?使い方|デイリーライトの?解説|デイリーライトの?動画/, 
  responses: "https://youtu.be/mm-KlYLtb-8?si=cLwUFJNwd7WyZmFI", type: "static" },
{ pattern: /火種必要数|光のカケラ必要数|光のかけら必要数|火種表|光のかけら表|光のかけら表|デイリーライトの?表/, 
  responses: "https://cdn.discordapp.com/attachments/1002997996855754943/1187964375798128780/e5f8620dd439bd75.png", type: "static" },
{ pattern: /ターボジャンプ/, 
  responses: "これやね。https://twitter.com/2hily_/status/1762483268761313679?t=-4miRA_kuN8OhJ3biHloNg&s=19", type: "static" },
{ pattern: /15本キャンマラ|おぷるさんコラボ|コラボ動画/, 
  responses: "https://youtu.be/epPPfpmS99M", type: "static" },
{ pattern: /楽園の?ルート|楽園の?キャンマラル|楽園の動画/, 
  responses: "https://youtu.be/rNgUpMXk2AQ", type: "static" },
{ pattern: /レコキャンの?使い方|レコキャンの?動画|レコキャンの?テク|レコキャンの?時短テク|シェアメモの?使い方|シェアメモの?動画|シェアメモの?テク|シェアメモの?時短テク/, 
  responses: "https://youtu.be/rNgUpMXk2AQ", type: "static" },
{ pattern: /孤島の?精霊一覧|孤島の?全ての精霊|孤島の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Koto-all.png?v=1711574878049/"], type: "static" },
{ pattern: /草原の?精霊一覧|草原の?全ての精霊|草原の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Sogen-all.png?v=1711574877247"], type: "static" },
{ pattern: /雨林の?精霊一覧|雨林の?全ての精霊|雨林の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Urin-all.png?v=1711574876227"], type: "static" },
{ pattern: /峡谷の?精霊一覧|峡谷の?全ての精霊|峡谷の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Kyokoku-all.png?v=1711574875272"], type: "static" },
{ pattern: /捨て?地の?精霊一覧|捨て?地の?全ての精霊|捨て?地の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Suteti-all.png?v=1711574874537"], type: "static" },
{ pattern: /書庫の?精霊一覧|書庫の?全ての精霊|書庫の?全精霊/, 
  responses: ["こちらをご覧ください。（9-bit様より引用）", "https://cdn.glitch.global/68ce99b8-0619-4731-b98b-b5d54a5d616e/Syoko-all.png?v=1711574878830"], type: "static" },
  
  { pattern: /AAA/,
    responses: ["BBB"],
    type: "static"
  },
  { pattern: /AAA/,
    responses: ["BBB"],
    type: "static"
  },
  { pattern: /VC開始/,
    responses: ["chatroom1にて通話が開始されました！\nhttps://discord.gg/PpugjHBgDB"],
    type: "static"
  },
  {
    pattern: /Kテスト/,
    responses: ["これはテストメッセージです。", "すべて正常に動作しています。"],
    type: "static"
  },

  // reverse-delete ＝ 一括表示し、順に削除
  {
    pattern: /うんこ|うんち|ウンコ|ウンチ|ｳﾝｺ|ｳﾝﾁ|💩/,
    responses: ["う", "ん", "こ", "だ", "な", "♪"],
    type: "reverse-delete"
  },

  // "progressive ＝ 1つ表示→削除。次を表示→削除
  {
    pattern: /せいは/,
    responses: [
      "せいさんはですね・・・。",
      "言いたい事たくさんあるんですよ。",
      "結構長くなるので覚悟してくださいね？",
      "何から話そうかな。",
      "まずは僕と青酸がはじめて出会った日の事ですが、",
      "あれはまだ僕たちが高3だった頃…の2年前…。",
      "続きは課金してね！♡"
    ],
    type: "progressive"
  },
  {
    pattern: /死ね|アホ|あほ|クソ|くそ|バカ|ばか/,
    responses: [
      "おい！",
      "そんなこと言うなよ！",
      "‥‥‥‥‥‥",
      "# ｸｿｶﾞ"
    ],
    type: "progressive"
  }
];
